### ISSUE TITLE
Replace Bootstrap with BassCSS

### ISSUE THREAD

**Issue by mattrothenberg** [mattrothenberg/styleguide-boilerplate#2]
I've gotten some feedback that it's confusing how some of the files in the `styles` directory, e.g., [`_alert.scss`](https://github.com/mattrothenberg/styleguide-boilerplate/blob/master/styles/_alert.scss) are empty, and yet components still get created when the styleguide is built.

This is because I'm pulling in Bootstrap via CDN in the `styleguide-theme` directory. 

To that end, does it make more sense to replace Bootstrap with a library like [BassCSS](http://www.basscss.com/), where the majority of the components have to be rolled by hand? I think it would better illustrate the workflow we encourage Designers to take.

**Comment by paulfarino** [comment]
If the designer knows how to build a layout in Bootstrap the project becomes less intimidating.  It would allow them to focus on Hologram and building out the styleguide vs the additional overhead of understanding the framework being used.

Possible solutions
- Bring in Bootstrap locally and don't call the CDN
- Build more custom components ontop of Bootstrap

I do like BassCSS. BassCSS really pushes to be more object oriented. Thoughts @abhisharma2

**Comment by abhisharma2** [comment]
tbh I hadn't heard of BassCSS, but whoa I like the look of it 👍  (apologies, my design toolkit skillz have diminished). 

I tend to agree with your first point @paulfarino, if the project is meant to be a boilerplate, then all components (.scss) files should have their own CSS in them, so lets just bring in Bootstrap locally. Whether it's Bootstrap, BassCSS, or any other CSS framework, it's not meant to be opinionated on that. 

Another idea could be adding a Wiki to show that you can mix CSS frameworks (like Bootstrap) with custom components (like the `.card`). After all, this is what most folks do. Maybe add a toggle that switches BassCSS with Bootstrap.

**Comment by mattrothenberg** [comment]
Yep, I totally see where you all are coming from!

I'll make a PR where Bootstrap is pulled in locally (in this first iteration, I think we ought to skip Bower / NPM, and just chuck `bootstrap-sass` into the styles directory.

Stay tuned!
