### ISSUE TITLE
Easy deploy?

### ISSUE THREAD

**Issue by abhisharma2** [mattrothenberg/styleguide-boilerplate#4]
@mattrothenberg @paulfarino should we add steps here to help designers get the styleguide up to a live URL?

**Comment by mattrothenberg** [comment]
@abhisharma2 @paulfarino Yes please!

Can we add steps for both Heroku and PWS? I know Paul has the PWS steps in his back pocket ;)

**Comment by paulfarino** [comment]
I added instructions for PWS to the `add-pws-to-readme` branch.

Possible solutions to deploy:
- Create a `gulp build` task to build -> Then use a Makefile or Rake task to deploy
- Create a `gulp deploy` task using gulp-shell. Here we can remove a step and run shell commands via gulp.

I'll add steps to deploy to Heroku this week. 
Nice-to-have: Deploy to Heroku button

**Comment by abhisharma2** [comment]
sweet @paulfarino - let me know if I can help

**Comment by mattrothenberg** [comment]
Closing this one. You guys rock!
