### ISSUE TITLE
Create wiki?

### ISSUE THREAD

**Issue by abhisharma2** [mattrothenberg/styleguide-boilerplate#9]
should we create a wiki area? basically shorten the README and direct folks to wiki instead. Gives more ability to break down the styleguide. wiki could be broken down to:
1. Orientation
2. Deployment
3. Examples (I'm in the midst of using this to create my co's styleguide 👍 )
4. External Resources (links to Hologram, et al)
5. ?? 

this would keep only the Installation steps in the README - short & sweet. push back if this isn't a good idea, 🍺  infused Friday thoughts, thats all - 😁 .

**Comment by mattrothenberg** [comment]
I think this is a good idea, @abhisharma2!

If the problem is that users have to scroll through a huge README, another lean (intermediate) solution might be to add a table of contents. If that doesn't do the trick, a Wiki seems like the appropriate next step.

Thoughts?
